# Giai đoạn build
FROM node:18-alpine AS builder

WORKDIR /app

# Sao chép file package
COPY manager/frontend/package*.json ./
RUN npm ci

# Sao chép source code
COPY manager/frontend/ .

# Biên dịch ứng dụng
RUN npm run build

RUN ls -a 

# Giai đoạn runtime
FROM nginx:alpine
LABEL org.opencontainers.image.source="https://github.com/namlevia/Xiaozhi-Esp32-Server-Go-Vi"

# Sao chép kết quả build
COPY --from=builder /app/dist /usr/share/nginx/html

# Sao chép file diagnose.js
COPY manager/frontend/diagnose.js /usr/share/nginx/html/

# Sao chép cấu hình nginx
COPY manager/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
